import searchIndex from '@/data/catalog/search-index.json';
import { normalizeExerciseText } from '@/lib/catalog/catalog-schema';

// Browser-safe view of the catalog: pt-BR names and search terms, keyed by any
// name an exercise may carry (catalog name or legacy per-account name).
// Generated by scripts/build-catalog-index.mjs.

interface IndexEntry {
  name: string;
  namePtBr: string;
  legacyNames: string[];
  terms: string[];
}

const entries = (searchIndex as { entries: IndexEntry[] }).entries;

const byName = new Map<string, IndexEntry>();
for (const entry of entries) {
  byName.set(normalizeExerciseText(entry.name), entry);
  for (const legacy of entry.legacyNames) {
    const key = normalizeExerciseText(legacy);
    if (!byName.has(key)) byName.set(key, entry);
  }
}

// Curated pt-BR name of a catalog exercise, or null for custom exercises.
export function catalogPtBrName(name: string): string | null {
  return byName.get(normalizeExerciseText(name))?.namePtBr ?? null;
}

// Search terms (aliases, pt-BR and English names) of a catalog exercise, or
// none for a custom one.
export function exerciseSearchTerms(name: string): string[] {
  return byName.get(normalizeExerciseText(name))?.terms ?? [];
}

// True when every word of the query appears in the exercise's name, its
// displayed name or one of its catalog search terms (accent- and
// case-insensitive): "puxada" finds "Puxada alta aberta", "pulley" finds it
// too through its alias.
export function matchesExerciseQuery(name: string, displayName: string, query: string): boolean {
  const words = normalizeExerciseText(query).split(' ').filter(Boolean);
  if (words.length === 0) return true;
  const haystack = [
    normalizeExerciseText(name),
    normalizeExerciseText(displayName),
    ...(byName.get(normalizeExerciseText(name))?.terms ?? []),
  ].join(' | ');
  return words.every((word) => haystack.includes(word));
}
